{% set name = "choicemodels" %}
{% set version = "0.2.1" %}
{% set sha256 = "c30ed3f307e34fce5995ac8c2eeccd2cf22ad6afabc13b260c5255553d15ee90" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - future
    - numpy
    - pandas
    - patsy
    - pylogit
    - scipy
    - statsmodels

test:
  imports:
    - choicemodels

about:
  home: https://github.com/UDST/choicemodels
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Tools for discrete choice modeling'
  description: Choicemodels is a Python package for discrete choice modeling
  doc_url: http://choicemodels.readthedocs.io/
  dev_url: https://github.com/UDST/choicemodels

extra:
  recipe-maintainers:
    - gboeing
    - smmaurer
