travis:
  secure:
    BINSTAR_TOKEN: upZ1xTy1GxFl8YGtB4E0MZi0o6YHryz25Efd2xSOPIxPmN2WFWf+GpQ7WETbzrBAT0SSaSMGt4kAZFnj2k71LrXszXfcjouYHKZlMYFFIECg06BUf8PbV93lsmVSREECraRO00n8mcjAFYcEb53UA2ZqX1/Gy9BgWo5bnUSn4yJ9xk6reHW3wJhrJ186DbvYITm/elLYuBb28aUiGGF4AO8aaIcxA3LrG6cn7sHXndDHpPTP5x1ln2vjl6BW0/9P0ymkTmJ1gx66AcRArwd4LqSgHuzVEn1WplBtkkaHz+Gp4bH1+EUJsxJt2FH3b4iYpLV6cCb+wTz3mIaBASfCSqglC8DrhiuBwXHHvHigb1F1fjcn/v3oF6K1mSppHwwS7+0AR7O2ziMTGE7jSboQvtVBjwqUni7Bc6oLzulrj/5XdvRPfKwNvlEgJWv1thi/+IMedNXxoheQqgvrfPm721mgfwhetodRTdxtfOro25wgLWXVftQdPcfo6zj10GqApIkOp8/xiuB03V+ptX2z4pwvOuXxoeeE1pG9YKNDuGoRXPMwUOcT7m8yKvJl42l0IHpkCOxL9x4g1SwPNNKOF3WcsrN6DOrG1QsAyYREYZzAFPliqh/ofa8JOQfB576IDVs/qDgKEtJzZqmv5HIhWBQoV4UqXrdWZ/SerzN3UUs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
