travis:
  secure:
    BINSTAR_TOKEN: t/zMCZhR3D3CbNiyFkJoaKu1pncGSuo5ZRIS1/3Shh/cW84ilC11UaTRG2zj6dH+uGSVb/zEdpQX48m7UTF30ZQmLoHIXGs9QiP/hsf1c3X56y68YPFc1Qwltcsi5Y+vVd0KDO7RB7vYN49+KWw5H7AQRDuZ4JOIFeTJWgFWNUCWS3ql6XssUiZCvj8DZv65u6FQfSculUTcYOFT5DMDoLRf7SbNn4bjzSiDe1GNexoAKV65RmZ5avv4lCZcRbZE+aFwJfD5mtAwAVm0NorVhbknp3Pgjwbkph3kP/CpXvgFhvfsfMVxNGx920XW5MeK8LEhz6HgdDgIPN5vQiGJvLeQhmraVEe9EmtKggZsALb8ojnWlOZYpoO67BBrag6Mnfps+LvKLTOyEwBSfn59eyQX0t17f7Spl8oFB4kOf3oIpNckaGxY/28GyVL2E/F44tjqrbfDIJrYqzaRonhZ/cl+tX+JjDczP92w8YdAxpb6rgJfd10yldXNXUHRW2ZCkTTHoslcyCHS+K+OOj5qhFWGkPG3FsqT2Z99pio9mA9Vb8iQCE3FsTNX52AI2KgR+46h2i9DpCHCTP/6BT2vbuGdijUggCXDEAaZgLPWI57EFDdaJjCXrjQmMiRERjbJZ6xLoywdcNhzd/udPl8+F/3VCELN5XeXPJSt/79JF3I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
